spring.application.name=vehicle-maintenance-api
server.port=8080
spring.jackson.time-zone=UTC
camunda.workflow.enabled=${CAMUNDA_WORKFLOW_ENABLED:true}
camunda.process-id=${CAMUNDA_PROCESS_ID:Process_VehicleMaintenanceRequest}
camunda.first-step-actor=${CAMUNDA_FIRST_STEP_ACTOR:movement_officer}
camunda.bpmn-resource=${CAMUNDA_BPMN_RESOURCE:vehicle-maintenance-request.bpmn}
camunda.operate-base-url=${CAMUNDA_OPERATE_BASE_URL:http://localhost:8081}
camunda.tasklist-base-url=${CAMUNDA_TASKLIST_BASE_URL:http://localhost:8082}
camunda.zeebe-gateway2=${CAMUNDA_ZEEBE_REST_BASE_URL:http://localhost:8088}
camunda.zeebe-grpc-address=${CAMUNDA_ZEEBE_GRPC_ADDRESS:127.0.0.1:26500}
camunda.keycloak-token-url=${CAMUNDA_KEYCLOAK_TOKEN_URL:http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token}
camunda.keycloak-client-id=${CAMUNDA_KEYCLOAK_CLIENT_ID:zeebe}
camunda.keycloak-client-secret=${CAMUNDA_KEYCLOAK_CLIENT_SECRET:zecret}
